USE foltyn_db1;

CREATE TABLE BK_INVOICE
(
  ID        INT    AUTO_INCREMENT  NOT NULL,
  INVOICE_NUMBER  INT              NOT NULL,
  YEAR            INT              NOT NULL,
  COMPANY_NAME    VARCHAR(500)     NOT NULL,
  TOTAL_AMOUNT    DECIMAL(10,2)    NOT NULL,
  DATE_ISSUED     DATE                 NULL,
  DATE_DUE        DATE                 NULL,

  CONSTRAINT PK_BK_INVOICE  PRIMARY KEY (ID)
);
